name = "v2ray-worker"
main = "src/worker.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "settings", id = "20ba3a54501642e6a53c243915f5f92f" }
]
